# Generated by Django 6.0.4 on 2026-04-16 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.TextField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.empleado')),
                ('id_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.login')),
            ],
            options={
                'verbose_name_plural': 'Bitácoras',
            },
        ),
    ]
