# Generated by Django 6.0.4 on 2026-04-16 21:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.empleado')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=300, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.empleado')),
                ('id_pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operaciones.pedido')),
            ],
            options={
                'verbose_name_plural': 'Notas de Venta',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
    ]
