# Generated by Django 6.0.4 on 2026-04-16 21:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('ci_o_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estados Civiles',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id_salario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'Salarios',
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id_tipo_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('ci', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('cel', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.estado')),
                ('id_estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.estadocivil')),
                ('id_nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.nacionalidad')),
                ('id_salario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.salario')),
                ('id_tipo_contacto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.tipocontacto')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.turno')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_login', models.DateTimeField(blank=True, null=True)),
                ('id_empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.empleado')),
            ],
            options={
                'verbose_name_plural': 'Logins',
            },
        ),
    ]
