# Generated by Django 6.0.4 on 2026-04-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
