# Generated by Django 6.0.4 on 2026-04-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_login_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='pribilegios_como_adm',
            field=models.BooleanField(default=False),
        ),
    ]
