# Generated by Django 6.0.4 on 2026-04-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_empleado_pribilegios_como_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='encargado',
            field=models.BooleanField(default=False),
        ),
    ]
