# Generated by Django 6.0.4 on 2026-04-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_empleado_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='personas.estado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='personas.estadocivil'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='personas.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_salario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='personas.salario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_tipo_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='personas.tipocontacto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='personas.turno'),
        ),
    ]
